name: Build and deploy

on:
  push:
    branches:
      - main  # Update this to your main branch
  release:
    types: [created]

env:
  GIT_USER: 'GitHub Actions'
  GIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16  # Update this to your required Node.js version
      - name: Install dependencies
        run: yarn
      - name: Build application
        run: yarn build
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test:coverage
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_CONFIG_NAME: ${{ env.GIT_USER }}
          GIT_CONFIG_EMAIL: ${{ env.GIT_EMAIL }}
          BRANCH: gh-pages  # Update this if using a different branch for deployment
          FOLDER: build
          CLEAN: true
